# my global config
global:
  scrape_interval:     1s # Set the scrape interval to every 1 second
  evaluation_interval: 1s # Evaluate rules every 1 second
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'kafka-exporter-source'
    static_configs:
      - targets: 
        - 'kafka-exporter-source:9308'
        - 'kafka-exporter-source-2:9308'
    scrape_interval: 1s
