---
producers:
  - name: producer1
    host: aerospike
    port: 3000
    namespace: producer
    set: users

consumers:
  - name: consumer1
    host: aerospike2
    port: 3000
    namespace: consumer_north
    set: users
  - name: consumer2
    host: aerospike2
    port: 3000
    namespace: consumer_central_and_south
    set: users_central
  - name: consumer3
    host: aerospike2
    port: 3000
    namespace: consumer_central_and_south
    set: users_south

region_mapping:
  "north": ["consumer1"]
  "central": ["consumer2"]
  "south": ["consumer3"]

region_groups:
  north:
    unchanged:
      - Ha Noi
      - Lai Chau
      - Dien Bien
      - Son La
      - Lang Son
      - Quang Ninh
      - Cao Bang
    merged:
      Tuyen Quang:
        - Ha Giang
      Lao Cai:
        - Yen Bai
      Thai Nguyen:
        - Bac Kan
      Phu Tho:
        - Vinh Phuc
        - Hoa Binh
      Bac Ninh:
        - Bac Giang
      Hung Yen:
        - Thai Binh
      Hai Phong:
        - Hai Duong
      Ninh Binh:
        - Ha Nam
        - Nam Dinh

  central:
    unchanged:
      - Hue
      - Thanh Hoa
      - Nghe An
      - Ha Tinh
    merged:
      Quang Tri:
        - Quang Binh
      Da Nang:
        - Quang Nam
      Quang Ngai:
        - Kon Tum
      Gia Lai:
        - Binh Dinh
      Khanh Hoa:
        - Ninh Thuan
      Lam Dong:
        - Dak Nong
        - Binh Thuan
      Dak Lak:
        - Phu Yen

  south:
    merged:
      TP. Ho Chi Minh:
        - Binh Duong
        - Ba Ria Vung Tau
      Dong Nai:
        - Binh Phuoc
      Tay Ninh:
        - Long An
      Can Tho:
        - Soc Trang
        - Hau Giang
      Vinh Long:
        - Ben Tre
        - Tra Vinh
      Dong Thap:
        - Tien Giang
      Ca Mau:
        - Bac Lieu
      An Giang:
        - Kien Giang
        
kafka:
  broker: source-kafka:29092,source-kafka-2:29092

performance:
  max_retries: 5
  worker_pool:
    producer: 1
    consumer: 2
  rate_control:
    initial_rate: 15000.0
    max_rate: 30000.0
    min_rate: 4000.0
    lag_threshold: 3000
    monitoring_interval_seconds: 10
    rate_adjustment_steps: 5
    max_rate_change_percent: 20.0 