---
producers:
  - name: producer1
    host: 127.0.0.1
    port: 3000
    namespace: producer
    set: users

consumers:
  - name: consumer1
    host: 127.0.0.1
    port: 4000
    namespace: consumer_north
    set: users
  - name: consumer2
    host: 127.0.0.1
    port: 4000
    namespace: consumer_central_and_south
    set: users_central
  - name: consumer3
    host: 127.0.0.1
    port: 4000
    namespace: consumer_central_and_south
    set: users_south

region_mapping:
  "north": ["consumer1"]
  "central": ["consumer2"]
  "south": ["consumer3"]

region_groups:
  north:
    - Ha Noi
    - Lai Chau
    - Dien Bien
    - Son La
    - Lang Son
    - Quang Ninh
    - Cao Bang
    - Tuyen Quang
    - Ha Giang
    - Lao Cai
    - Yen Bai
    - Thai Nguyen
    - Bac Kan
    - Phu Tho
    - Vinh Phuc
    - Hoa Binh
    - Bac Ninh
    - Bac Giang
    - Hung Yen
    - Thai Binh
    - Hai Phong
    - Hai Duong
    - Ninh Binh
    - Ha Nam
    - Nam Dinh

  central:
    - Thanh Hoa
    - Nghe An
    - Ha Tinh
    - Quang Tri
    - Quang Binh
    - Thua Thien Hue
    - Da Nang
    - Quang Nam
    - Quang Ngai
    - Kon Tum
    - Gia Lai
    - Binh Dinh
    - Khanh Hoa
    - Ninh Thuận
    - Lam Dong
    - Dak Nong
    - Binh Thuan
    - Dak Lak
    - Phu Yen

  south:
    - TP. Ho Chi Minh
    - Binh Duong
    - Ba Ria Vung Tau
    - Dong Nai
    - Binh Phuoc
    - Tay Ninh
    - Long An
    - Can Tho
    - Soc Trang
    - Hau Giang
    - Vinh Long
    - Ben Tre
    - Tra Vinh
    - Dong Thap
    - Tien Giang
    - Ca Mau
    - Bac Lieu
    - An Giang
    - Kien Giang

kafka:
  broker: localhost:9092

performance:
  max_messages_per_second: 4000
  max_retries: 5
  worker_pool:
    producer: 2
    consumer: 4
  rate_control:
    initial_rate: 5000.0
    max_rate: 10000.0
    min_rate: 1000.0
    lag_threshold: 1000
    monitoring_interval_seconds: 10
    rate_adjustment_steps: 5
    max_rate_change_percent: 0.2
