apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-servicemonitor
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: kafka-metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zookeeper-servicemonitor
  labels:
    app: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: zookeeper-metrics
      interval: 30s