{
 "title": "Aerospike Batch Transactions View",
 "description": "Dashboard helps visualise multiple stats at batch transaction processing including read, write, delete, proxy, tsvc etc.,",
 "tags": [
  "Monitoring",
  "Namespace",
  "usecase"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\", cluster_name=~\"$cluster|$^\"},service)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(aerospike_namespace_objects{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\" },ns)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total (rate)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    rate(aerospike_namespace_batch_sub_delete_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_batch_sub_lang_delete_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_batch_sub_lang_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_batch_sub_lang_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_batch_sub_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(\n    rate(aerospike_namespace_batch_sub_delete_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\nrate(aerospike_namespace_batch_sub_lang_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\nrate(aerospike_namespace_batch_sub_proxy_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\nrate(aerospike_namespace_batch_sub_read_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\nrate(aerospike_namespace_batch_sub_tsvc_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\nrate(aerospike_namespace_batch_sub_udf_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\nrate(aerospike_namespace_batch_sub_write_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
     "legendFormat": "Errors"
    },
    {
     "expr": "sum(\n    rate(aerospike_namespace_batch_sub_delete_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_batch_sub_read_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n\n)",
     "legendFormat": "Not Found"
    },
    {
     "expr": "sum(\n    rate(aerospike_namespace_batch_sub_delete_filtered_out{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_batch_sub_read_filtered_out{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_batch_sub_udf_filtered_out{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_batch_sub_write_filtered_out{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n\n)",
     "legendFormat": "Filtered out"
    },
    {
     "expr": "sum(\n    rate(aerospike_namespace_batch_sub_delete_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_batch_sub_proxy_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_batch_sub_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_batch_sub_tsvc_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_batch_sub_udf_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_batch_sub_write_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
     "legendFormat": "Timeout"
    }
   ]
  },
  {
   "title": "Read",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_read_success",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Filtered out (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_read_filtered_out",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_read_filtered_out{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Error (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_read_error ",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_read_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Not Found (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_read_not_found",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_read_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Timeout (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_read_timeout",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Read - From Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_read_success from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Filtered out (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_read_filtered_out from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_read_filtered_out{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Error (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_read_error from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_read_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Not found (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_read_not_found from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_read_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Timeout (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_read_timeout from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Write",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_write_success",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Filtered out (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_write_filtered_out",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_write_filtered_out{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Error (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_write_error",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_write_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Timeout (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_write_timeout",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_write_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Write - From Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_write_success from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Filtered out (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_write_filtered_out from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_write_filtered_out{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Error (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_write_error from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_write_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Timeout (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_write_timeout from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_write_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Delete",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_delete_success",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_delete_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Filtered out (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_delete_filtered_out",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_delete_filtered_out{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Error (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_delete_error",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_delete_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Not Found (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_delete_not_found",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_delete_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Timeout (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_delete_timeout",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_delete_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Delete - From Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_delete_success from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_delete_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Filtered out (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_delete_filtered_out from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_delete_filtered_out{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Error (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_delete_error from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_delete_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Not Found (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_delete_not_found from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_delete_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Timeout (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_delete_timeout from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_delete_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    }
   ]
  },
  {
   "title": "UDF",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Complete (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_udf_complete ",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_udf_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Filtered out (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_udf_filtered_out",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_udf_filtered_out{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Error (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_udf_error",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_udf_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Timeout (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_udf_time_out",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_udf_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    }
   ]
  },
  {
   "title": "UDF - From Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Complete (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_udf_complete from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_udf_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Filtered out (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_udf_filtered_out from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_udf_filtered_out{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Error (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_udf_error from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_udf_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Timeout (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_udf_timeout from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_udf_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Lang",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Delete Success (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_lang_delete_success",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_lang_delete_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Error (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_lang_error",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_lang_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Read Success (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_lang_read_success",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_lang_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Write Success (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_lang_write_success",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_lang_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Lang - From Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Delete Success (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_lang_delete_success from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_lang_delete_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Error (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_lang_error from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_lang_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Read Success (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_lang_read_success from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_lang_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Write Success (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of batch_sub_lang_write_success from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_lang_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TSVC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_tsvc_error",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_tsvc_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Timeout (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_tsvc_timeout",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_tsvc_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TSVC - From Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_tsvc_error from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_tsvc_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Timeout (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_tsvc_timeout from proxy",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_from_proxy_batch_sub_tsvc_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Complete (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_proxy_complete",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_proxy_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Error (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_proxy_error",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_proxy_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Timeout (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_proxy_timeout",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_proxy_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    }
   ]
  }
 ]
}