{
 "title": "Tổng quan Kafka Exporter",
 "description": "Kafka resource usage and throughput",
 "tags": [ "Kafka" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kafka_consumergroup_current_offset, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kafka_consumergroup_current_offset{job=~\"$job\"}, instance)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_topic_partition_current_offset{instance='$instance',topic!='__consumer_offsets',topic!='--kafka'}, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "So sánh tốc độ đọc và ghi của topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=\"$topic\"}[1s]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{instance=~\"$instance\", topic=~\"$topic\"}[1s])) by (consumergroup, topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tổng số message trong topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{instance=\"$instance\", topic=~\"$topic\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Độ trễ theo Consumer Group",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{instance=\"$instance\",topic=~\"$topic\"}",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Số message gửi vào mỗi giây",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_topic_partition_current_offset{instance=~'$instance', topic=~\"$topic\"}[1s])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Số message tiêu thụ mỗi giây",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{instance=~\"$instance\", topic=~\"$topic\"}[1s])) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Số partition theo Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partitions{instance=\"$instance\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}