apiVersion: apps/v1
kind: Deployment
metadata:
  name: aerospike
  namespace: aerospike
  labels:
    app: aerospike
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aerospike
  template:
    metadata:
      labels:
        app: aerospike
    spec:
      containers:
      - name: aerospike
        image: aerospike/aerospike-server:latest
        ports:
        - containerPort: 3000
        - containerPort: 3001
        - containerPort: 3002
        volumeMounts:
        - name: aerospike-storage
          mountPath: /opt/aerospike/data
      volumes:
      - name: aerospike-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: aerospike
spec:
  ports:
  - name: client
    port: 3000
    targetPort: 3000
  - name: mesh
    port: 3001
    targetPort: 3001
  - name: info
    port: 3002
    targetPort: 3002
  selector:
    app: aerospike