{
 "title": "Tổng quan Kafka Exporter 2",
 "description": "Kafka resource usage and throughput",
 "tags": [ "Kafka" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kafka_consumergroup_current_offset, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kafka_consumergroup_current_offset{job=~\"$job\"}, instance)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_topic_partition_current_offset{instance='$instance',topic!='__consumer_offsets',topic!='--kafka'}, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Tổng số mesage đã được tiêu thụ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_consumergroup_current_offset",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tổng số message đến topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{instance=\"$instance\", topic=~\"$topic\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "So sánh tốc độ đọc và ghi của topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=\"$topic\"}[3s]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{instance=~\"$instance\", topic=~\"$topic\"}[3s])) by (consumergroup, topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Số message gửi vào mỗi giây",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "irate(kafka_topic_partition_current_offset{instance=~'$instance', topic=~\"$topic\"}[3s])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Số message tiêu thụ mỗi giây",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(irate(kafka_consumergroup_current_offset{instance=~\"$instance\", topic=~\"$topic\"}[3s])) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Độ trễ theo Consumer Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{instance=\"$instance\",topic=~\"$topic\"}",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Số partition theo Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partitions{instance=\"$instance\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}