{
 "title": "Kafka Metrics (2s) - Original Ver2",
 "description": "Kafka metrics with 2-second aggregation",
 "tags": [ "Kafka" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "label_values(up, job)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kafka_brokers{job=\"$job\"}, instance)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_topic_partition_current_offset{instance='$instance',topic!='__consumer_offsets',topic!='--kafka'}, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Message Rate Comparison (2s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(kafka_topic_partition_current_offset{instance=~'$instance', topic=~\"$topic\"}[2s]))",
     "legendFormat": "Producer Rate"
    },
    {
     "expr": "sum(irate(kafka_consumergroup_current_offset{instance=~\"$instance\", topic=~\"$topic\"}[2s])) by (consumergroup, topic)",
     "legendFormat": "Consumer Rate ({{consumergroup}})"
    }
   ]
  },
  {
   "title": "Producer Message Rate (2s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(irate(kafka_topic_partition_current_offset{instance=~'$instance', topic=~\"$topic\"}[2s]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Message Rate (2s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(irate(kafka_consumergroup_current_offset{instance=~\"$instance\", topic=~\"$topic\"}[2s])) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Total Messages Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{instance=~\"$instance\", topic=~\"$topic\"})",
     "legendFormat": "Total Produced Messages (Unique)"
    },
    {
     "expr": "sum(kafka_consumergroup_current_offset{instance=~\"$instance\", topic=~\"$topic\"})",
     "legendFormat": "Total Consumer Messages"
    }
   ]
  },
  {
   "title": "Consumer Lag by Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "clamp_min(kafka_consumergroup_lag{instance=\"$instance\",topic=~\"$topic\"}, 0)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}}) - Lag"
    }
   ]
  }
 ]
}