# Aerospike database configuration file
# Node replica của cluster aerospike2
service {
	cluster-name docker2
}

logging {
	console {
		context any info
	}
}

network {
	service {
		address any
		port 3000
	}

	heartbeat {
		mode mesh
		address any
		port 3002
		interval 150
		timeout 10
        mesh-seed-address-port 172.29.0.2 3002
	}

	fabric {
		address any
		port 3001
	}
}

namespace consumer_north {
	replication-factor 2
	default-ttl 0
	nsup-period 120
	storage-engine device {
		file /opt/aerospike/data/consumer_north.dat
		filesize 4G
		read-page-cache true
	}
}

namespace consumer_central_and_south {
	replication-factor 2
	default-ttl 0
	nsup-period 120
	storage-engine device {
		file /opt/aerospike/data/consumer_central_and_south.dat
		filesize 4G
		read-page-cache true
	}
} 