# Aerospike database configuration file
# Node replica của cluster aerospike2
service {
	cluster-name docker2
	user root
	group root

	# Số luồng service tốt nhất = 3 × vCPU (nếu 2 vCPU thì đặt 6)
	service-threads 6
	proto-fd-max 50000
}

logging {
	console {
		context any info
	}
}

network {
	service {
		address any
		port 3000
	}

	heartbeat {
		mode mesh
		address any
		port 3002
		mesh-seed-address-port 172.28.0.4 3002
		mesh-seed-address-port 172.28.0.5 3002
		interval 150
		timeout 10
	}

	fabric {
		address any
		port 3001
	}
}

namespace consumer_north {
	replication-factor 2
	default-ttl 0
	stop-writes-sys-memory-pct 95
	evict-indexes-memory-pct 30
	storage-engine device {
		file /opt/aerospike/data/consumer_north.dat
		filesize 10G
		flush-size 256K
		max-write-cache 256M
		defrag-lwm-pct 30
		evict-used-pct 95
	}
}

namespace consumer_central_and_south {
	replication-factor 2
	default-ttl 0
	stop-writes-sys-memory-pct 95
	evict-indexes-memory-pct 30
	storage-engine device {
		file /opt/aerospike/data/consumer_central_and_south.dat
		filesize 10G
		flush-size 256K
		max-write-cache 256M
		defrag-lwm-pct 30
		evict-used-pct 95
	}
} 