producers:
  - name: producer1
    host: 127.0.0.1
    port: 3000
    namespace: producer
    set: users

consumers:
  - name: consumer1
    host: 127.0.0.1
    port: 4000
    namespace: consumer_033
    set: users
  - name: consumer2
    host: 127.0.0.1
    port: 4000
    namespace: consumer_096
    set: users

prefix_mapping:
  "096": ["consumer1"]
  "033": ["consumer2"]
